### ISSUE TITLE
setup error

### ISSUE THREAD

**Issue by cheron5** [vladmandic/pigallery#21]
Hi,
I've tried using both git clone and the release .tar.gz file and I get the same error:
OS: Ubuntu 22.04.4

```
npm run setup
npm WARN using --force Recommended protections disabled.

> @vladmandic/pigallery@3.9.2 setup
> node ./setup.js

/home/cheron/src/pigallery/setup.js:102
  const meta = npm.prune?.audit?.metadata;
                         ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
```
./setup.js vs npm run setup was the same, but didn't have the npm WARNing messages.

Any suggestions?

Thanks
-chuck

**Comment by vladmandic** [comment]
i haven't updated this repo for the past 2 years, i'm guessing some of the packages changed so need to find exact version that works. but i don't have time for it right now, i think i'm going to archive this project, sorry.
