### ISSUE TITLE
Installation error / esbuild

### ISSUE THREAD

**Issue by fly-man-** [vladmandic/pigallery#9]
Debian 11 / NodeJS 14.18

When running the application it keeps yelling about esbuild not working properly. Any ideas what might be causing this ?

```
> @vladmandic/pigallery@3.7.6 start /opt/pigallery
> node --unhandled-rejections=strict --pending-deprecation --trace-deprecation --stack-size=8192 --max-old-space-size=8192 --optimize-for-size server/pigallery.js

2021-10-01 11:43:04 INFO:  @vladmandic/pigallery version 3.7.6
2021-10-01 11:43:04 INFO:  User: root Platform: linux Arch: x64 Node: v14.18.0
2021-10-01 11:43:04 STATE: Application log: /opt/pigallery/pigallery.log
2021-10-01 11:43:04 INFO:  Authentication required: true
2021-10-01 11:43:04 INFO:  Media root: media/
2021-10-01 11:43:04 INFO:  Allowed image file types: [ '.jpeg', '.jpg', [length]: 2 ]
2021-10-01 11:43:04 STATE: Change log updated: /opt/pigallery/CHANGELOG.md
2021-10-01 11:43:04 DATA:  Build sources: [ 'client/compare/compare.ts', 'client/index/index.ts', 'client/process/process.ts', 'client/video/video.ts', [length]: 4 ] [ 'client/index/worker.ts', 'client/index/pwa-serviceworker.ts', [length]: 2 ]
/opt/pigallery/node_modules/esbuild/bin/esbuild:2
throw new Error(`esbuild: Failed to install correctly
^

Error: esbuild: Failed to install correctly

Make sure you don't have "ignore-scripts" set to true. You can check this with
"npm config get ignore-scripts". If that returns true you can reset it back to
false using "npm config set ignore-scripts false" and then reinstall esbuild.

If you're using npm v7, make sure your package-lock.json file contains either
"lockfileVersion": 1 or the code "hasInstallScript": true. If it doesn't have
either of those, then it is likely the case that a known bug in npm v7 has
corrupted your package-lock.json file. Regenerating your package-lock.json file
should fix this issue.

    at Object.<anonymous> (/opt/pigallery/node_modules/esbuild/bin/esbuild:2:7)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47
2021-10-01 11:43:04 ERROR: Client application build error {}
2021-10-01 11:43:04 INFO:  Database engine: nedb
2021-10-01 11:43:04 STATE: Image DB backup exists: backup/pigallery.db-2021-10-01.gz
2021-10-01 11:43:04 STATE: Monitoring: [ 'config.json', 'package.json', 'server', 'client', [length]: 4 ]
2021-10-01 11:43:04 STATE: Image DB loaded: pigallery.db records: 0
2021-10-01 11:43:04 STATE: Mounted: auth from (client/auth.html
2021-10-01 11:43:04 STATE: Mounted: compare from (client/compare.html
2021-10-01 11:43:04 STATE: Mounted: index from (client/index.html
2021-10-01 11:43:04 STATE: Mounted: offline from (client/offline.html
2021-10-01 11:43:04 STATE: Mounted: process from (client/process.html
2021-10-01 11:43:04 STATE: Mounted: video from (client/video.html
2021-10-01 11:43:04 STATE: RESTful API ready
2021-10-01 11:43:05 STATE: Loaded WordNet database: assets/wordnet-synset.json 60942 terms in 24034816 bytes
2021-10-01 11:43:06 STATE: Loaded all cities database: assets/cities.json 195175 all cities 4426 large cities
2021-10-01 11:43:10 STATE: Server HTTP listening: { address: '::', family: 'IPv6', port: 10010 }
2021-10-01 11:43:10 STATE: Server HTTPS listening: { address: '::', family: 'IPv6', port: 10011 }

```

**Comment by vladmandic** [comment]
i cannot reproduce the issue, just tried clean install
but i pushed some minor updates just now  

can you do a fresh install?

```shell
git clone --depth 1 https://github.com/vladmandic/pigallery
cd pigallery
npm run setup
npm run start
```

and check output of `npm config get ignore-scripts`

if the problem persists, upload generated `setup.json`  
(it's a bit big to post to github issues, maybe you can create a gist with it)

**Comment by fly-man-** [comment]
After a clean installation including Yarn it's now working properly

**Comment by vladmandic** [comment]
i'm glad its resolved.
